services:
  mysql:
    image: mysql:9.7.2

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_ROOT_PASSWORD}
      MYSQL_USER: ${ENV_MYSQL_USER}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
      MYSQL_DATABASE: transporte

    volumes:
      - transporte-onibus-db:/var/lib/mysql

volumes:
  transporte-onibus-db: